=== opengeospatial/ogc_api_coverages/standard/common/part_2/openapi/schemas/collectionDesc.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Collection Description Schema",
    "description": "This schema defines metadata resource returned from /collections/{collectionId}.",
    "type": "object",
    "required": [
        "id",
        "links"
        ],
    "properties": {
        "id": {
            "description": "identifier of the collection used, for example, in URIs",
            "type": "string"
            },
        "title": {
            "description": "human readable title of the collection",
            "type": "string"
            },
        "description": {
            "description": "a description of the members of the collection",
            "type": "string"
            },
        "attribution" : {
            "type" : "string",
            "title" : "attribution for the collection",
            "description" : "The `attribution` should be short and intended for presentation to a user, for example, in a corner of a map. Parts of the text can be links to other resources if additional information is needed. The string can include HTML markup."
            },
        "links": {
            "type": "array",
            "items": {"$href": "link.json"}
            },
        "extent": {"$href": "extent.json"},
        "itemType": {
            "description": "An indicator about the type of the items in the collection.",
            "type": "string"
            },
        "crs": {
            "description": "the list of coordinate reference systems supported by the API; the first item is the default coordinate reference system",
            "type": "array",
            "items": {
                "type": "string"
                },
            "default": [
                "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
                ],
            "example": [
                "http://www.opengis.net/def/crs/OGC/1.3/CRS84",
                "http://www.opengis.net/def/crs/EPSG/0/4326"
                ]
            }
        }
    }

=== opengeospatial/ogc_api_coverages/standard/common/part_2/openapi/examples/CollectionDescriptionExample.json
{
  "id": "1234567890",
  "title": "Example Collection Description Response",
  "description": "This is an example of a Collection Description in JSON format",
  "attribution": "<a href='www.ign.es' rel=' '>IGN</a> <a href='www.govdata.de/dl-de/by-2-0'>(c)</a>",
  "links": [
    { "href": "http://data.example.org/collections.json",
      "rel": "self", "type": "application/json", "title": "this document" },
    { "href": "http://data.example.org/collections.html",
      "rel": "alternate", "type": "text/html", "title": "this document as HTML" },
    { "href": "http://schemas.example.org/1.0/foobar.xsd",
      "rel": "describedBy", "type": "application/xml", "title": "XML schema for Acme Corporation data" }
  ],
  "extent": {
    "spatial": [ 7.01, 50.63, 7.22, 50.78 ],
    "temporal": [ "2010-02-15T12:34:56Z", "2018-03-18T12:11:00Z" ]
    }
}
